---
- name: Install MySQL
  apt: package=mysql-server state=present
  sudo: yes

- name: Create MySQL Configuration File
  template: src=mysql.cnf.j2 dest=/etc/my.cnf
  sudo: yes
  notify:
    - Restart MySQL
